theme = "everforest_dark"

[editor]
bufferline = "multiple"
color-modes = true
completion-replace = true
cursorline = true
idle-timeout = 0
line-number = "relative"
scrolloff = 8
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
parents = true

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true

[editor.statusline]
center = ["version-control"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"#" = "toggle_comments"
V = "extend_line"
tab = ":buffer-next"
C-tab = ":buffer-previous"
space.x = ":buffer-close"
esc = ["keep_primary_selection"]
space.R = ":config-reload"
space.W = ":write!"
